# Generated by Django 4.0.5 on 2022-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
