# Generated by Django 4.0.5 on 2022-07-15 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0003_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
