# Generated by Django 4.0.5 on 2022-07-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_estado'),
        ('pedidos', '0005_remove_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
