# Generated by Django 4.0.5 on 2022-07-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_lineapedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido',
            new_name='pedidos',
        ),
    ]
