# Generated by Django 4.0.5 on 2022-07-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_rename_pedido_lineapedido_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedidos',
            new_name='pedido',
        ),
    ]
