# Generated by Django 4.0.5 on 2022-07-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_rename_pedidos_lineapedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='estado',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
