# Generated by Django 4.0.5 on 2022-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=30, null=True, verbose_name='Correo Cliente'),
        ),
    ]
