# Generated by Django 4.0.5 on 2022-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='precio'),
        ),
    ]
