# Generated by Django 4.0.5 on 2022-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
